/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.glb --types 
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tesla-roadster-2020-wwwvecarzcom-fac3d813620f4c4a95da1933c2592069
Title: Tesla Roadster 2020 | www.vecarz.com
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    roadster080_Brake_Disc_0: THREE.Mesh
    roadster002_Thread_0: THREE.Mesh
    roadster002_Sidewall_0: THREE.Mesh
    ['TRDEF-WheelFtR_Rims_0']: THREE.Mesh
    ['TRDEF-WheelFtR_mirror_0']: THREE.Mesh
    ['TRDEF-WheelFtR_Metal_-_Black_rough_0']: THREE.Mesh
    roadster005_grill_0: THREE.Mesh
    roadster082_car_main_paint_0: THREE.Mesh
    roadster007_Glass_mid_tint_0: THREE.Mesh
    roadster008_interior_0: THREE.Mesh
    roadster009_seats_0: THREE.Mesh
    roadster010_seats_0: THREE.Mesh
    roadster011_mirror_0: THREE.Mesh
    ['roadster012_Metal_-_Black_rough_0']: THREE.Mesh
    ['roadster013_Metal_-_Black_rough_0']: THREE.Mesh
    ['roadster014_Metal_-_Black_rough_0']: THREE.Mesh
    roadster015_car_main_paint_0: THREE.Mesh
    ['roadster016_Metal_-_Black_rough_0']: THREE.Mesh
    ['roadster017_Metal_-_Black_rough_0']: THREE.Mesh
    roadster018_non_lustrous_metal_0: THREE.Mesh
    roadster019_Glass_mid_tint_0: THREE.Mesh
    ['roadster020_Metal_-_Black_rough_0']: THREE.Mesh
    ['roadster021_Metal_-_Black_rough_0']: THREE.Mesh
    roadster022_grill_0: THREE.Mesh
    roadster022_non_lustrous_metal_0: THREE.Mesh
    roadster024_carbon_fibre_0: THREE.Mesh
    roadster025_Glass_Amber_0: THREE.Mesh
    ['roadster026_Metal_-_Black_rough_0']: THREE.Mesh
    roadster026_indicator_left_0: THREE.Mesh
    roadster026_indicator_right_0: THREE.Mesh
    roadster027_chrome_0: THREE.Mesh
    roadster028_carbon_fibre_0: THREE.Mesh
    roadster029_Glass_Clear_0: THREE.Mesh
    roadster030_carbon_fibre_0: THREE.Mesh
    roadster031_carbon_fibre_0: THREE.Mesh
    roadster032_headlights_AHO_0: THREE.Mesh
    roadster032_carbon_fibre_0: THREE.Mesh
    roadster033_headlights_AHO_0: THREE.Mesh
    roadster033_carbon_fibre_0: THREE.Mesh
    roadster034_carbon_fibre_0: THREE.Mesh
    roadster035_headlights_main_0: THREE.Mesh
    roadster036_carbon_fibre_0: THREE.Mesh
    roadster037_Glass_Clear_0: THREE.Mesh
    roadster038_chrome_0: THREE.Mesh
    roadster039_chrome_0: THREE.Mesh
    roadster040_carbon_fibre_0: THREE.Mesh
    ['roadster041_Metal_-_Black_rough_0']: THREE.Mesh
    roadster042_mirror_0: THREE.Mesh
    roadster043_carbon_fibre_0: THREE.Mesh
    roadster044_Glass_Clear_0: THREE.Mesh
    ['roadster045_Metal_-_Black_rough_0']: THREE.Mesh
    roadster046_Glass_Tint_max_0: THREE.Mesh
    roadster047_non_lustrous_metal_0: THREE.Mesh
    roadster048_Glass_Clear_0: THREE.Mesh
    ['roadster049_Metal_-_Black_rough_0']: THREE.Mesh
    roadster049_licence_plate_light_0: THREE.Mesh
    roadster050_Glass_rear_lights_main_0: THREE.Mesh
    roadster051_Glass_Amber_0: THREE.Mesh
    ['roadster052_Metal_-_Black_rough_0']: THREE.Mesh
    roadster052_indicator_left_0: THREE.Mesh
    roadster052_indicator_right_0: THREE.Mesh
    roadster053_Glass_mid_tint_0: THREE.Mesh
    roadster054_Glass_mid_tint_0: THREE.Mesh
    ['roadster055_Metal_-_Black_rough_0']: THREE.Mesh
    roadster056_Glass_Tint_max_0: THREE.Mesh
    roadster057_Glass_Tint_max_0: THREE.Mesh
    roadster058_car_main_paint_0: THREE.Mesh
    roadster059_Glass_mid_tint_0: THREE.Mesh
    roadster060_car_main_paint_0: THREE.Mesh
    roadster061_ior_1_0: THREE.Mesh
    roadster062_car_main_paint_0: THREE.Mesh
    roadster063_carbon_fibre_0: THREE.Mesh
    roadster064_Glass_rear_lights_main_0: THREE.Mesh
    roadster065_Glass_rear_lights_DHO_0: THREE.Mesh
    roadster066_Glass_Clear_0: THREE.Mesh
    roadster067_carbon_fibre_0: THREE.Mesh
    roadster068_carbon_fibre_0: THREE.Mesh
    roadster069_Glass_rear_lights_main_0: THREE.Mesh
    ['roadster070_Metal_-_Black_rough_0']: THREE.Mesh
    roadster071_mirror_0: THREE.Mesh
    roadster077_mirror_0: THREE.Mesh
    roadster079_mirror_0: THREE.Mesh
    ['TRDEF-Body_car_main_paint_0']: THREE.Mesh
    ['TRDEF-WheelBrakeFtR_calipers_0']: THREE.Mesh
    roadster072_Brake_Disc_0: THREE.Mesh
    roadster001_Thread_0: THREE.Mesh
    roadster001_Sidewall_0: THREE.Mesh
    ['TRDEF-WheelFtL_Rims_0']: THREE.Mesh
    ['TRDEF-WheelFtL_mirror_0']: THREE.Mesh
    ['TRDEF-WheelFtL_Metal_-_Black_rough_0']: THREE.Mesh
    ['TRDEF-WheelBrakeFtL_calipers_0']: THREE.Mesh
    roadster074_Brake_Disc_0: THREE.Mesh
    roadster003_Thread_0: THREE.Mesh
    roadster003_Sidewall_0: THREE.Mesh
    ['TRDEF-WheelBkL_Rims_0']: THREE.Mesh
    ['TRDEF-WheelBkL_mirror_0']: THREE.Mesh
    ['TRDEF-WheelBkL_Metal_-_Black_rough_0']: THREE.Mesh
    ['TRDEF-WheelBrakeBkL_calipers_0']: THREE.Mesh
    roadster076_Brake_Disc_0: THREE.Mesh
    roadster004_Thread_0: THREE.Mesh
    roadster004_Sidewall_0: THREE.Mesh
    ['TRDEF-WheelBkR_Rims_0']: THREE.Mesh
    ['TRDEF-WheelBkR_mirror_0']: THREE.Mesh
    ['TRDEF-WheelBkR_Metal_-_Black_rough_0']: THREE.Mesh
    ['TRDEF-WheelBrakeBkR_calipers_0']: THREE.Mesh
  }
  materials: {
    Brake_Disc: THREE.MeshStandardMaterial
    Thread: THREE.MeshStandardMaterial
    Sidewall: THREE.MeshPhysicalMaterial
    Rims: THREE.MeshPhysicalMaterial
    mirror: THREE.MeshStandardMaterial
    ['Metal_-_Black_rough']: THREE.MeshStandardMaterial
    grill: THREE.MeshStandardMaterial
    car_main_paint: THREE.MeshPhysicalMaterial
    Glass_mid_tint: THREE.MeshPhysicalMaterial
    interior: THREE.MeshStandardMaterial
    seats: THREE.MeshStandardMaterial
    non_lustrous_metal: THREE.MeshStandardMaterial
    carbon_fibre: THREE.MeshPhysicalMaterial
    Glass_Amber: THREE.MeshPhysicalMaterial
    indicator_left: THREE.MeshStandardMaterial
    indicator_right: THREE.MeshStandardMaterial
    chrome: THREE.MeshStandardMaterial
    Glass_Clear: THREE.MeshPhysicalMaterial
    headlights_AHO: THREE.MeshStandardMaterial
    headlights_main: THREE.MeshStandardMaterial
    Glass_Tint_max: THREE.MeshPhysicalMaterial
    licence_plate_light: THREE.MeshStandardMaterial
    Glass_rear_lights_main: THREE.MeshStandardMaterial
    ior_1: THREE.MeshStandardMaterial
    Glass_rear_lights_DHO: THREE.MeshStandardMaterial
    calipers: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export type RoadsterConfig = {
  paint: string
  contrast: 'chrome' | 'blackout'
  wheels: 'silver' | 'dark'
  interior: 'black' | 'cream'
}

type RoadsterProps = React.JSX.IntrinsicElements['group'] & {
  config?: RoadsterConfig
  onLoaded?: () => void
}

const DEFAULT_CONFIG: RoadsterConfig = {
  paint: '#E31C23',
  contrast: 'chrome',
  wheels: 'silver',
  interior: 'black',
}

export function Roadster({ config = DEFAULT_CONFIG, onLoaded, ...props }: RoadsterProps) {
  const { nodes, materials } = useGLTF('/scene.glb') as unknown as GLTFResult

  useEffect(() => {
    onLoaded?.()
  }, [materials, onLoaded])

  useEffect(() => {
    const carPaint = materials.car_main_paint
    const chrome = materials.chrome
    const rims = materials.Rims
    const interior = materials.interior
    const seats = materials.seats

    carPaint.color.set(config.paint)
    chrome.color.set(config.contrast === 'blackout' ? '#151515' : '#D8D8D8')
    rims.color.set(config.wheels === 'dark' ? '#202225' : '#B7BBC0')
    interior.color.set(config.interior === 'cream' ? '#C9B79C' : '#151515')
    seats.color.set(config.interior === 'cream' ? '#E1D4BE' : '#242424')
  }, [config, materials])

  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.574, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-83.803, 31.333, 153.422]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[0.06, 0, 0]}>
              <mesh geometry={nodes.roadster002_Thread_0.geometry} material={materials.Thread} />
              <mesh geometry={nodes.roadster002_Sidewall_0.geometry} material={materials.Sidewall} />
            </group>
            <mesh geometry={nodes['TRDEF-WheelFtR_Rims_0'].geometry} material={materials.Rims} />
            <mesh geometry={nodes['TRDEF-WheelFtR_mirror_0'].geometry} material={materials.mirror} />
            <mesh geometry={nodes['TRDEF-WheelFtR_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} />
            <mesh geometry={nodes.roadster080_Brake_Disc_0.geometry} material={materials.Brake_Disc} position={[0.1, 0, 0]} />
          </group>
          <group position={[0, 54.137, -2.142]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[0.003, -0.683, 0.413]}>
              <mesh geometry={nodes.roadster007_Glass_mid_tint_0.geometry} material={materials.Glass_mid_tint} />
              <mesh geometry={nodes.roadster082_car_main_paint_0.geometry} material={materials.car_main_paint} position={[-0.003, 0.683, -0.413]} />
            </group>
            <group position={[0, 1.146, 0.368]}>
              <mesh geometry={nodes.roadster022_grill_0.geometry} material={materials.grill} />
              <mesh geometry={nodes.roadster022_non_lustrous_metal_0.geometry} material={materials.non_lustrous_metal} />
            </group>
            <group position={[0, -1.928, -0.138]}>
              <mesh geometry={nodes['roadster026_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} />
              <mesh geometry={nodes.roadster026_indicator_left_0.geometry} material={materials.indicator_left} />
              <mesh geometry={nodes.roadster026_indicator_right_0.geometry} material={materials.indicator_right} />
            </group>
            <group position={[0, -2.088, -0.053]}>
              <mesh geometry={nodes.roadster032_headlights_AHO_0.geometry} material={materials.headlights_AHO} />
              <mesh geometry={nodes.roadster032_carbon_fibre_0.geometry} material={materials.carbon_fibre} />
            </group>
            <group position={[0, -2.018, -0.037]}>
              <mesh geometry={nodes.roadster033_headlights_AHO_0.geometry} material={materials.headlights_AHO} />
              <mesh geometry={nodes.roadster033_carbon_fibre_0.geometry} material={materials.carbon_fibre} />
            </group>
            <group position={[0, 2.132, 0.121]}>
              <mesh geometry={nodes['roadster049_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} />
              <mesh geometry={nodes.roadster049_licence_plate_light_0.geometry} material={materials.licence_plate_light} />
            </group>
            <group position={[0, 1.779, -0.175]}>
              <mesh geometry={nodes['roadster052_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} />
              <mesh geometry={nodes.roadster052_indicator_left_0.geometry} material={materials.indicator_left} />
              <mesh geometry={nodes.roadster052_indicator_right_0.geometry} material={materials.indicator_right} />
            </group>
            <mesh geometry={nodes['TRDEF-Body_car_main_paint_0'].geometry} material={materials.car_main_paint} />
            <mesh geometry={nodes.roadster005_grill_0.geometry} material={materials.grill} position={[0, -2.221, -0.359]} />
            <mesh geometry={nodes.roadster008_interior_0.geometry} material={materials.interior} position={[0, -0.049, 0.217]} />
            <mesh geometry={nodes.roadster009_seats_0.geometry} material={materials.seats} position={[0, 0.103, -0.065]} />
            <mesh geometry={nodes.roadster010_seats_0.geometry} material={materials.seats} position={[0, 0.29, 0.398]} />
            <mesh geometry={nodes.roadster011_mirror_0.geometry} material={materials.mirror} position={[0.002, -0.183, 0.501]} />
            <mesh geometry={nodes['roadster012_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[0, -0.205, 0.497]} />
            <mesh geometry={nodes['roadster013_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[0, 1.166, 0.372]} />
            <mesh geometry={nodes['roadster014_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[0.349, -0.462, 0.108]} />
            <mesh geometry={nodes.roadster015_car_main_paint_0.geometry} material={materials.car_main_paint} position={[0, -0.465, -0.015]} />
            <mesh geometry={nodes['roadster016_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[0, 0.772, 0.385]} />
            <mesh geometry={nodes['roadster017_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[0, 0.332, 0.396]} />
            <mesh geometry={nodes.roadster018_non_lustrous_metal_0.geometry} material={materials.non_lustrous_metal} position={[0, -0.683, 0.276]} />
            <mesh geometry={nodes.roadster019_Glass_mid_tint_0.geometry} material={materials.Glass_mid_tint} position={[0, -0.769, 0.241]} />
            <mesh geometry={nodes['roadster020_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[0, -0.779, 0.245]} />
            <mesh geometry={nodes['roadster021_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[0, -0.68, 0.411]} />
            <mesh geometry={nodes.roadster024_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, -2.198, -0.427]} />
            <mesh geometry={nodes.roadster025_Glass_Amber_0.geometry} material={materials.Glass_Amber} position={[0, -1.928, -0.139]} />
            <mesh geometry={nodes.roadster027_chrome_0.geometry} material={materials.chrome} position={[0, -1.137, 0.051]} />
            <mesh geometry={nodes.roadster028_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, -1.667, -0.049]} />
            <mesh geometry={nodes.roadster029_Glass_Clear_0.geometry} material={materials.Glass_Clear} position={[0, -2.058, -0.04]} />
            <mesh geometry={nodes.roadster030_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, -2.061, -0.037]} />
            <mesh geometry={nodes.roadster031_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, -2.069, -0.065]} />
            <mesh geometry={nodes.roadster034_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, -2.012, -0.037]} />
            <mesh geometry={nodes.roadster035_headlights_main_0.geometry} material={materials.headlights_main} position={[0, -2.019, -0.037]} />
            <mesh geometry={nodes.roadster036_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, -2.002, -0.037]} />
            <mesh geometry={nodes.roadster037_Glass_Clear_0.geometry} material={materials.Glass_Clear} position={[0, -2.026, -0.037]} />
            <mesh geometry={nodes.roadster038_chrome_0.geometry} material={materials.chrome} position={[0, -2.21, -0.05]} />
            <mesh geometry={nodes.roadster039_chrome_0.geometry} material={materials.chrome} position={[-0.005, 2.103, 0.225]} />
            <mesh geometry={nodes.roadster040_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, -2.195, -0.365]} />
            <mesh geometry={nodes['roadster041_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[-0.001, -2.159, -0.31]} />
            <mesh geometry={nodes.roadster042_mirror_0.geometry} material={materials.mirror} />
            <mesh geometry={nodes.roadster043_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, 1.988, -0.272]} />
            <mesh geometry={nodes.roadster044_Glass_Clear_0.geometry} material={materials.Glass_Clear} position={[0, 2.113, -0.172]} />
            <mesh geometry={nodes['roadster045_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[0, 2.108, -0.171]} />
            <mesh geometry={nodes.roadster046_Glass_Tint_max_0.geometry} material={materials.Glass_Tint_max} position={[0, 2.135, 0.101]} />
            <mesh geometry={nodes.roadster047_non_lustrous_metal_0.geometry} material={materials.non_lustrous_metal} position={[0, 2.131, 0.104]} />
            <mesh geometry={nodes.roadster048_Glass_Clear_0.geometry} material={materials.Glass_Clear} position={[0, 2.132, 0.114]} />
            <mesh geometry={nodes.roadster050_Glass_rear_lights_main_0.geometry} material={materials.Glass_rear_lights_main} position={[0, 2.11, -0.171]} />
            <mesh geometry={nodes.roadster051_Glass_Amber_0.geometry} material={materials.Glass_Amber} position={[0, 1.779, -0.175]} />
            <mesh geometry={nodes.roadster053_Glass_mid_tint_0.geometry} material={materials.Glass_mid_tint} position={[0, 0.803, 0.386]} />
            <mesh geometry={nodes.roadster054_Glass_mid_tint_0.geometry} material={materials.Glass_mid_tint} position={[0, 1.079, 0.48]} />
            <mesh geometry={nodes['roadster055_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[0, 1.13, 0.466]} />
            <mesh geometry={nodes.roadster056_Glass_Tint_max_0.geometry} material={materials.Glass_Tint_max} position={[0, 0.138, 0.587]} />
            <mesh geometry={nodes.roadster057_Glass_Tint_max_0.geometry} material={materials.Glass_Tint_max} position={[0, 0.111, 0.557]} />
            <mesh geometry={nodes.roadster058_car_main_paint_0.geometry} material={materials.car_main_paint} position={[0, 0.105, 0.553]} />
            <mesh geometry={nodes.roadster059_Glass_mid_tint_0.geometry} material={materials.Glass_mid_tint} position={[0, -0.177, 0.35]} />
            <mesh geometry={nodes.roadster060_car_main_paint_0.geometry} material={materials.car_main_paint} position={[0, 2.046, 0.278]} />
            <mesh geometry={nodes.roadster061_ior_1_0.geometry} material={materials.ior_1} position={[0, 2.112, 0.27]} />
            <mesh geometry={nodes.roadster062_car_main_paint_0.geometry} material={materials.car_main_paint} position={[0, 2.084, 0.267]} />
            <mesh geometry={nodes.roadster063_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, 2.105, 0.27]} />
            <mesh geometry={nodes.roadster064_Glass_rear_lights_main_0.geometry} material={materials.Glass_rear_lights_main} position={[0, 2.112, 0.27]} />
            <mesh geometry={nodes.roadster065_Glass_rear_lights_DHO_0.geometry} material={materials.Glass_rear_lights_DHO} position={[0, 1.936, 0.215]} />
            <mesh geometry={nodes.roadster066_Glass_Clear_0.geometry} material={materials.Glass_Clear} position={[0, 1.837, 0.227]} />
            <mesh geometry={nodes.roadster067_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, 1.829, 0.227]} />
            <mesh geometry={nodes.roadster068_carbon_fibre_0.geometry} material={materials.carbon_fibre} position={[0, 1.914, 0.215]} />
            <mesh geometry={nodes.roadster069_Glass_rear_lights_main_0.geometry} material={materials.Glass_rear_lights_main} position={[0, 1.818, 0.226]} />
            <mesh geometry={nodes['roadster070_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} position={[0, -0.088, -0.253]} />
            <mesh geometry={nodes.roadster071_mirror_0.geometry} material={materials.mirror} />
            <mesh geometry={nodes.roadster077_mirror_0.geometry} material={materials.mirror} />
            <mesh geometry={nodes.roadster079_mirror_0.geometry} material={materials.mirror} />
          </group>
          <group position={[83.803, 31.331, 153.418]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[-0.06, 0, 0]}>
              <mesh geometry={nodes.roadster001_Thread_0.geometry} material={materials.Thread} />
              <mesh geometry={nodes.roadster001_Sidewall_0.geometry} material={materials.Sidewall} />
            </group>
            <mesh geometry={nodes['TRDEF-WheelFtL_Rims_0'].geometry} material={materials.Rims} />
            <mesh geometry={nodes['TRDEF-WheelFtL_mirror_0'].geometry} material={materials.mirror} />
            <mesh geometry={nodes['TRDEF-WheelFtL_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} />
            <mesh geometry={nodes.roadster072_Brake_Disc_0.geometry} material={materials.Brake_Disc} position={[-0.1, 0, 0]} />
          </group>
          <group position={[87.425, 34.127, -138.741]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[-0.071, 0, 0]}>
              <mesh geometry={nodes.roadster003_Thread_0.geometry} material={materials.Thread} />
              <mesh geometry={nodes.roadster003_Sidewall_0.geometry} material={materials.Sidewall} />
            </group>
            <mesh geometry={nodes['TRDEF-WheelBkL_Rims_0'].geometry} material={materials.Rims} />
            <mesh geometry={nodes['TRDEF-WheelBkL_mirror_0'].geometry} material={materials.mirror} />
            <mesh geometry={nodes['TRDEF-WheelBkL_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} />
            <mesh geometry={nodes.roadster074_Brake_Disc_0.geometry} material={materials.Brake_Disc} position={[-0.118, 0, 0]} />
          </group>
          <group position={[-84.02, 34.108, -138.74]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[0.071, 0, 0]}>
              <mesh geometry={nodes.roadster004_Thread_0.geometry} material={materials.Thread} />
              <mesh geometry={nodes.roadster004_Sidewall_0.geometry} material={materials.Sidewall} />
            </group>
            <mesh geometry={nodes['TRDEF-WheelBkR_Rims_0'].geometry} material={materials.Rims} />
            <mesh geometry={nodes['TRDEF-WheelBkR_mirror_0'].geometry} material={materials.mirror} />
            <mesh geometry={nodes['TRDEF-WheelBkR_Metal_-_Black_rough_0'].geometry} material={materials['Metal_-_Black_rough']} />
            <mesh geometry={nodes.roadster076_Brake_Disc_0.geometry} material={materials.Brake_Disc} position={[0.118, 0, 0]} />
          </group>
          <mesh geometry={nodes['TRDEF-WheelBrakeFtR_calipers_0'].geometry} material={materials.calipers} position={[-73.072, 31.338, 140.088]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['TRDEF-WheelBrakeFtL_calipers_0'].geometry} material={materials.calipers} position={[83.803, 31.331, 153.418]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['TRDEF-WheelBrakeBkL_calipers_0'].geometry} material={materials.calipers} position={[87.425, 34.127, -138.741]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['TRDEF-WheelBrakeBkR_calipers_0'].geometry} material={materials.calipers} position={[-84.02, 34.108, -138.74]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
